remote_theme: mmistakes/minimal-mistakes

title: ""   # leave blank if you don’t want text
logo: "Abhi_logo.png"   # path to your logo
logo_height: 100px

# Build settings
plugins:
  - jekyll-include-cache

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "Education"
    url: /education/
  - title: "Research"
    url: /research/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /cv/

# Minimal Mistakes theme font
fonts:
  heading:
    family: "Merriweather"
  body:
    family: "Lora"
