remote_theme: mmistakes/minimal-mistakes

# Build settings
plugins:
  - jekyll-include-cache

title: ""
logo: ""

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "Education"
    url: /education/
  - title: "Research"
    url: /research/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /cv/

# Minimal Mistakes theme font
fonts:
  heading:
    family: "Merriweather"
  body:
    family: "Lora"
